# version: "3.8"

services:
    collector_app:
        build: ./collector_app
        container_name: collector_app
        env_file:
            - ./collector_app/.env
        ports:
            - "8000:8000"
        depends_on:
            - rabbitmq
        networks:
            - micro_net

    celery_worker:
        build: ./celery_worker
        container_name: celery_worker
        env_file:
            - ./celery_worker/.env
        depends_on:
            - rabbitmq
            - postgres
        networks:
            - micro_net

    postgres:
        image: postgres:15
        container_name: postgres_db
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: micro_db
        volumes:
            - pg_data:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        networks:
            - micro_net

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_broker
        ports:
            - "5672:5672"
            - "15672:15672"
        networks:
            - micro_net

volumes:
    pg_data:

networks:
    micro_net:
        driver: bridge
