apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector-app
  labels:
    app: collector-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector-app
  template:
    metadata:
      labels:
        app: collector-app
    spec:
      containers:
      - name: collector-app
        image: collector-app:latest
        imagePullPolicy: Never  # Use local image built by minikube
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: app-config
        # Health checks
        livenessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: collector-app-service
spec:
  selector:
    app: collector-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
---
# NodePort service to expose the app externally
apiVersion: v1
kind: Service
metadata:
  name: collector-app-external
spec:
  selector:
    app: collector-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000
  type: NodePort
