apiVersion: v1
kind: PersistentVolumeClaim # requestes persistent storage from k8 cluster
metadata:
    name: postgres-pvc
spec:
    accessModes:
        - ReadWriteOnce # only one pod can read-write to it at a time
    resources:
        requests:
            storage: 0.5Gi # 0.5GB of storage requested

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    labels:
        app: postgres
spec:
    replicas: 1 # only one pod will run
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
        spec:
            containers:
                - name: postgres
                  image: postgres:15 # latest postgres image fron dockerhub
                  env:
                      - name: POSTGRES_USER
                        value: "postgres"
                      - name: POSTGRES_PASSWORD
                        value: "postgres"
                      - name: POSTGRES_DB
                        value: "micro_db"
                  ports: # which port to expose for pgsql connections
                      - containerPort: 5432
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data # mount the postgres-pvc here
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
    name: postgres-service
spec:
    selector:
        app: postgres
    ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
    type: ClusterIP
